---total revenue generated by male vs. female customers
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- used a discount but still spent more than the average purchase amount
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

---top 5 products with the highest average review rating
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5


-------
SELECT 
    "subscription_status" AS subscription_status,
    COUNT(DISTINCT "customer_id") AS num_customers,
    AVG("purchase_amount") AS avg_spend_per_customer,
    SUM("purchase_amount") AS total_revenue
FROM customer
GROUP BY "subscription_status";



--Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and count of each segment
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "number_of_customers" 
from customer_type 
group by customer_segment;

--top 3 most purchased products within each category
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-----5 products have the highest percentage of purchases with discounts
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
 
-----customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- revenue contribution of each age 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


